package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF386B1D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBCF293)
val md_theme_light_onPrimaryContainer = Color(0xFF052100)
val md_theme_light_secondary = Color(0xFF56624B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD7E8CD)
val md_theme_light_onSecondaryContainer = Color(0xFF151E0D)
val md_theme_light_tertiary = Color(0xFF386667)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBCECEE)
val md_theme_light_onTertiaryContainer = Color(0xFF002021)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF7F9F2)
val md_theme_light_onBackground = Color(0xFF1A1C18)
val md_theme_light_surface = Color(0xFFF7F9F2)
val md_theme_light_onSurface = Color(0xFF1A1C18)
val md_theme_light_surfaceVariant = Color(0xFFE1E3D9)
val md_theme_light_onSurfaceVariant = Color(0xFF43483E)
val md_theme_light_outline = Color(0xFF74796D)

val md_theme_dark_primary = Color(0xFFA1D57A)
val md_theme_dark_onPrimary = Color(0xFF0C3900)
val md_theme_dark_primaryContainer = Color(0xFF1F5204)
val md_theme_dark_onPrimaryContainer = Color(0xFFBCF293)
val md_theme_dark_secondary = Color(0xFFBBCBAF)
val md_theme_dark_onSecondary = Color(0xFF283420)
val md_theme_dark_secondaryContainer = Color(0xFF3E4A35)
val md_theme_dark_onSecondaryContainer = Color(0xFFD7E8CD)
val md_theme_dark_tertiary = Color(0xFFA0CFD1)
val md_theme_dark_onTertiary = Color(0xFF003738)
val md_theme_dark_tertiaryContainer = Color(0xFF1E4E4F)
val md_theme_dark_onTertiaryContainer = Color(0xFFBCECEE)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF12140F)
val md_theme_dark_onBackground = Color(0xFFE1E3D9)
val md_theme_dark_surface = Color(0xFF12140F)
val md_theme_dark_onSurface = Color(0xFFE1E3D9)
val md_theme_dark_surfaceVariant = Color(0xFF43483E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C8BC)
val md_theme_dark_outline = Color(0xFF8D9387)
